completed match-info-route and fixed creating ticket
nguyenvanxuanvu/TT_CNPM pull request #18
Opened 2022-04-04 15:18 UTC by mhung-afk

2022-04-05 16:43 UTC, ChienNguyenDac requested changes

2022-04-05 16:43 UTC, ChienNguyenDac commented on back-end/router/matchInfo.js
> +            .populate('product_index_id')
We can use `timeStart` & `dateStart` directly in Ticket model & skip population to `product_index`.
Skip check exists `SharingMatchInfo` because it is valid when going to check-can-edit.
With checking code, we can use `Ticket.findOne({match_info_id: matchId, code: passowrd})`

2022-04-05 16:43 UTC, ChienNguyenDac commented on back-end/router/ticket.js
> +                    await SharingMatchInfo.create({user:user_id, matchs: [match_info]})
`match_info` or `match_info._id` ?
Or do both works correctly?

2022-04-06 00:25 UTC, mhung-afk commented on back-end/router/matchInfo.js
> +            .populate('product_index_id')
I use populate at _product_index_ path to get _timeEnd_ of this _product_, which need to check editing had been timeout or not yet.

2022-04-06 00:31 UTC, mhung-afk commented on back-end/router/matchInfo.js
> +            .populate('product_index_id')
It is not only check exists _SharingMatchInfo_ but also check this match is shared for this user or not. I will optimize.

2022-04-06 00:38 UTC, closed without merging